name: Deploy SAM with Python

on:
    workflow_call:
      inputs:
        PYTHON_VERSION:
          required: false
          type: string
          description: 'The python version used in the SAM Application'
          default: '3.11'
        ENVIRONMENT:
          required: true
          type: string
          description: 'The sam app environment defined in samconfig.toml'
      secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
        AWS_SAM_REGION:
          required: true

jobs:
  deploy:
    name: Build & Deploy

    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: SetUp Python ${{ inputs.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: SetUp SAM CLI
        uses: aws-actions/setup-sam@v2
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_SAM_REGION }}

      - name: Build App
        run: sam build --config-env ${{ inputs.ENVIRONMENT }}

      - name: Deploy
        run: sam deploy --config-env ${{ inputs.ENVIRONMENT }} --no-confirm-changeset --no-fail-on-empty-changeset