on:
    workflow_call:
      inputs:
        RELEASE_VERSION:
          required: true
          type: string
          description: "The version to use for the release"
        RELEASE_TYPE:
          required: true
          type: string
          description: "The type of release, either release of fix"
      secrets:
        GIT_CONFIG_TOKEN:
          required: true
        GIT_CONFIG_USER:
          required: true
        GIT_CONFIG_USER_EMAIL:
          required: true

jobs:
  release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_CONFIG_TOKEN }}

      # Sets up the git user that used to push the version change
      - name: Configure Git user
        run: |
          git config user.email ${{ secrets.GIT_CONFIG_USER_EMAIL }}
          git config user.name ${{ secrets.GIT_CONFIG_USER }}
          
      - name: Update version
        uses: rahulp959/toml-editor@v1.0.1
        with:
          file: samconfig.toml
          key: sam.application.version
          value: ${{ inputs.RELEASE_VERSION }}

      - name: Update prod prefix parameter
        uses: rahulp959/toml-editor@v1.0.1
        with:
          file: samconfig.toml
          key: prod.deploy.parameters.s3_prefix
          value: prod/${{ github.repository }}/${{ inputs.RELEASE_VERSION }}
      
      - name: Update beta prefix parameter
        uses: rahulp959/toml-editor@v1.0.1
        with:
          file: samconfig.toml
          key: beta.deploy.parameters.s3_prefix
          value: beta/${{ github.repository }}/${{ inputs.RELEASE_VERSION }}
          
      - name: Create Release Branch
        run: |
          git checkout -b ${{ inputs.RELEASE_TYPE }}/${{ inputs.RELEASE_VERSION }}

      - name: Push version change ${{ inputs.RELEASE_VERSION }}
        run: |
          git add .
          git commit -m "Set version ${{ inputs.RELEASE_VERSION }}"
          git push -u origin ${{ inputs.RELEASE_TYPE }}/${{ inputs.RELEASE_VERSION }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ inputs.RELEASE_TYPE }}/${{ inputs.RELEASE_VERSION }}
          base: main
          title: Release version ${{ inputs.RELEASE_VERSION }}
          reviewers: ${{ github.actor }}
          body: |
            This PR was created in response to a manual trigger of the release workflow here:

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.